CREATE TABLE users (id UUID PRIMARY KEY, username TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, role TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE sessions (id UUID PRIMARY KEY, user_id UUID NOT NULL REFERENCES users(id), expires_at TIMESTAMPTZ NOT NULL, revoked_at TIMESTAMPTZ);
CREATE TABLE api_accounts (id UUID PRIMARY KEY, name TEXT NOT NULL, market TEXT NOT NULL, encrypted_key BYTEA NOT NULL, encrypted_secret BYTEA NOT NULL, enabled BOOLEAN NOT NULL DEFAULT false, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE devices (id UUID PRIMARY KEY, user_id UUID REFERENCES users(id), browser TEXT, ip INET, last_login TIMESTAMPTZ, last_activity TIMESTAMPTZ);
CREATE TABLE markets (id UUID PRIMARY KEY, name TEXT UNIQUE NOT NULL, enabled BOOLEAN NOT NULL DEFAULT false, mode TEXT NOT NULL DEFAULT 'DRY_RUN');
CREATE TABLE strategies (id UUID PRIMARY KEY, name TEXT NOT NULL, status TEXT NOT NULL, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE strategy_versions (id UUID PRIMARY KEY, strategy_id UUID REFERENCES strategies(id), checksum TEXT NOT NULL, status TEXT NOT NULL);
CREATE TABLE strategy_files (id UUID PRIMARY KEY, strategy_version_id UUID REFERENCES strategy_versions(id), filename TEXT NOT NULL, storage_key TEXT NOT NULL);
CREATE TABLE backtests (id UUID PRIMARY KEY, strategy_version_id UUID REFERENCES strategy_versions(id), metrics JSONB NOT NULL, started_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE trades (id UUID PRIMARY KEY, market TEXT NOT NULL, symbol TEXT NOT NULL, status TEXT NOT NULL, pnl NUMERIC, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE orders (id UUID PRIMARY KEY, trade_id UUID REFERENCES trades(id), external_id TEXT, status TEXT NOT NULL);
CREATE TABLE positions (id UUID PRIMARY KEY, market TEXT NOT NULL, symbol TEXT NOT NULL, status TEXT NOT NULL, quantity NUMERIC NOT NULL);
CREATE TABLE signals (id UUID PRIMARY KEY, source TEXT NOT NULL, payload JSONB NOT NULL, status TEXT NOT NULL, received_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE risk_events (id UUID PRIMARY KEY, reason TEXT NOT NULL, payload JSONB NOT NULL, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE audit_logs (id UUID PRIMARY KEY, user_id UUID, ip INET, action TEXT NOT NULL, result TEXT NOT NULL, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE ai_actions (id UUID PRIMARY KEY, action TEXT NOT NULL, approved_by UUID, status TEXT NOT NULL, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE servers (id UUID PRIMARY KEY, name TEXT NOT NULL, provider TEXT, ip INET, status TEXT NOT NULL);
CREATE TABLE telegram_accounts (id UUID PRIMARY KEY, name TEXT NOT NULL, encrypted_token BYTEA NOT NULL, enabled BOOLEAN DEFAULT false);
CREATE TABLE notifications (id UUID PRIMARY KEY, channel TEXT NOT NULL, message TEXT NOT NULL, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE system_settings (key TEXT PRIMARY KEY, value JSONB NOT NULL, updated_at TIMESTAMPTZ DEFAULT now());
