import './style.css';

type ApiAccount={id:string;name:string;market:string;enabled:boolean;last_check?:string};
type Readiness={allowed:boolean;reason:string};
type Health={status:string;live_trading:string};
type StrategyScan={status:string;checksum?:string;findings?:string[];reason:string};
const apiBase=(import.meta.env.VITE_API_BASE_URL??'').replace(/\/$/,'');
const api=async<T>(path:string,init?:RequestInit):Promise<T>=>{const response=await fetch(`${apiBase}/api/v1${path}`,{credentials:'include',headers:{...(init?.body instanceof FormData?{}:{'Content-Type':'application/json'}),...(init?.headers??{})},...init});if(response.status===401){showLogin('انتهت الجلسة، يرجى تسجيل الدخول.');throw new Error('انتهت الجلسة')}if(response.status===403)throw new Error('ليس لديك صلاحية الوصول إلى هذه البيانات.');if(!response.ok)throw new Error((await response.json().catch(()=>({detail:'تعذر الاتصال بالخادم'}))).detail);return response.json() as Promise<T>};
const empty=(text='لا توجد بيانات متاحة حالياً')=>`<div class="empty">${text}</div>`;
const table=(headers:string[],emptyText='لا توجد بيانات متاحة حالياً')=>`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody><tr><td colspan="${headers.length}">${emptyText}</td></tr></tbody></table></div>`;
const markets=['Binance Spot','Cross Margin','Isolated Margin','USDⓈ-M Futures','COIN-M Futures','Alpha','Stocks'];
const nav=[['overview','الرئيسية'],['markets-view','الأسواق'],['positions','المراكز'],['orders','الأوامر'],['strategies','الاستراتيجيات'],['signals','الإشارات'],['alpha','Alpha'],['risk','المخاطر'],['backtesting','Backtesting'],['accounts','حسابات التداول'],['providers','AI Providers'],['sources','مصادر الإشارات'],['workflow','سير العمل'],['reports','التقارير'],['settings','الإعدادات']];
const app=document.querySelector<HTMLDivElement>('#app')!;
app.innerHTML=`<div class="terminal"><aside class="sidebar"><div class="brand"><i>α</i><span>ALPHA<br><small>TRADING</small></span></div><nav>${nav.map(([id,label],i)=>`<a class="${i===0?'active':''}" href="#${id}">${label}</a>`).join('')}</nav></aside><div class="shell"><header><div><p class="eyebrow">TRADING OPERATIONS CENTER</p><h1>ALPHA TRADING</h1></div><div class="header-actions"><span id="system-status" class="badge neutral">● جار التحقق</span><span id="connection" class="badge neutral">🟡 RECONNECTING</span><button class="icon" aria-label="التنبيهات" onclick="location.hash='notifications'">🔔</button><button class="user" id="user-menu">المستخدم</button><button class="text-button" id="logout" disabled title="لا يوجد Logout API حاليًا">خروج</button></div></header><main>
<section id="overview" class="hero"><div><p class="eyebrow">SYSTEM OVERVIEW</p><h2>مركز عمليات التداول</h2><p class="subtle">كل القيمة المعروضة مصدرها API. الحقول التي لا يوفرها Backend تبقى فارغة.</p></div><button id="kill-switch" class="danger">⛔ إيقاف التداول</button></section>
<section class="overview-grid">${['System Status','Trading Status','API Connections','Active Strategies','Open Positions','Open Orders','Risk Status','Alpha Engine','AI Assistant'].map(label=>`<article class="metric"><span>${label}</span>${empty()}</article>`).join('')}</section>
<section><div class="section-heading"><div><p class="eyebrow">PORTFOLIO</p><h2>المحفظة والتعرّض</h2></div></div><div class="metric-grid">${['Equity','Available Balance','Used Margin','Realized PNL','Unrealized PNL','Daily PNL','Drawdown','Exposure'].map(label=>`<article class="metric"><span>${label}</span>${empty()}</article>`).join('')}</div></section>
<section id="markets-view"><div class="section-heading"><div><p class="eyebrow">TRADING VENUES</p><h2>الأسواق</h2></div></div><div class="market-grid">${markets.map(name=>`<article class="market-card"><div class="section-heading"><h3>${name}</h3><span class="badge neutral">—</span></div><p class="subtle">Connection · Balance · PNL · Trades · Strategy · Position · Risk · Last Activity</p>${empty()}</article>`).join('')}</div></section>
<section class="two-col"><article class="panel"><div class="section-heading"><h2>السوق المباشر</h2><span class="subtle">WebSocket</span></div><div id="live-market">${empty('الاتصال بالسوق غير متاح')}</div></article><article id="risk" class="panel"><div class="section-heading"><h2>مركز المخاطر</h2><span id="risk-status" class="badge neutral">غير متاح</span></div><div class="risk-list">${['Daily Loss','Maximum Drawdown','Exposure','Open Positions','Leverage','Spread','Slippage','Cooldown','Kill Switch'].map(x=>`<div><span>${x}</span><b>—</b></div>`).join('')}</div><p id="readiness-reason" class="subtle">جار قراءة قرار المخاطر من الخادم…</p></article></section>
<section id="positions" class="panel"><div class="section-heading"><h2>المراكز المفتوحة</h2><span class="subtle">Open Positions</span></div>${table(['Exchange','Symbol','Side','Entry Price','Current Price','Quantity','Leverage','Unrealized PNL','Stop Loss','Take Profit','Risk','Time'],'لا توجد مراكز مفتوحة')}</section>
<section id="orders" class="panel"><div class="section-heading"><h2>الأوامر الأخيرة</h2><span class="subtle">Recent / Open Orders</span></div>${table(['Order ID','Symbol','Side','Type','Price','Quantity','Status','Exchange','Time'])}</section>
<section id="alpha" class="panel"><div class="section-heading"><h2>Alpha Engine</h2><span class="subtle">Backend results only</span></div><div class="alpha-grid">${['Market Regime','Strategy Ranking','Signal Score','Position Size','Capital Allocation','Performance','Performance Decay','Confidence'].map(x=>`<div><span>${x}</span><b>—</b></div>`).join('')}</div><p class="subtle">لا يوجد منطق Alpha أو قرار تداول في المتصفح.</p></section>
<section id="strategies" class="panel"><div class="section-heading"><h2>مدير الاستراتيجيات</h2><span class="badge neutral">لا يوجد API للاستراتيجيات</span></div>${table(['Strategy Name','Version','Status','Market','Timeframe','Performance','Risk','Last Run','Last Update'],'لم تتم إضافة استراتيجية')}<details><summary>رفع استراتيجية للفحص الأمني</summary><p class="subtle">تُرسل إلى مسار الفحص الموجود فقط؛ لا تُشغّل من الواجهة.</p><form id="strategy-form"><label>ملف الاستراتيجية<input name="file" type="file" accept=".py,.json,.yaml,.yml,.toml,.txt,.zip" required></label><button id="scan-submit">رفع وفحص</button><button type="reset" class="text-button">إلغاء</button></form><p id="scan-status" class="subtle" role="status"></p><pre id="scan-result"></pre></details></section>
<section id="signals" class="panel"><div class="section-heading"><h2>الإشارات</h2><span class="badge neutral">لا يوجد API للإشارات المخزنة</span></div>${table(['Symbol','Direction','Signal Score','Entry','SL','TP1','TP2','TP3','TP4','TP5','TP6','TP7','Risk','Status','Source','Time'])}</section>
<section id="accounts" class="panel"><div class="section-heading"><div><h2>حسابات التداول والاتصالات</h2><p class="subtle">API Secret لا يظهر بعد الحفظ ولا يُخزن في المتصفح.</p></div><button class="text-button" id="add-account">إضافة حساب</button></div><div id="accounts-list">${empty('جار تحميل حسابات التداول…')}</div><details id="account-details"><summary>نموذج حساب تداول</summary><form id="account-form"><label>اسم الحساب<input name="name" required placeholder="اسم الحساب"></label><label>نوع السوق<select name="market"><option value="spot">Binance Spot</option><option value="cross_margin">Cross Margin</option><option value="isolated_margin">Isolated Margin</option><option value="usds_m">USDⓈ-M</option><option value="coin_m">COIN-M</option><option value="alpha">Alpha</option><option value="stocks">Stocks</option></select></label><label>API Key<input name="api_key" required autocomplete="off" placeholder="أدخل API Key"></label><label>Secret Key<input name="api_secret" required type="password" autocomplete="new-password" placeholder="أدخل Secret Key"></label><p class="subtle">Environment وIP Restriction وTest Connection لا تدعمها API الحالية بعد.</p><button id="account-submit">حفظ مشفر</button><button type="reset" class="text-button">إلغاء</button></form><p id="account-status" class="subtle" role="status"></p></details></section>
<section id="providers" class="panel"><div class="section-heading"><h2>AI Providers</h2><span class="badge neutral">Backend API مطلوب</span></div>${empty('لم يتم إعداد مزود الذكاء الاصطناعي')}<p class="subtle">يتطلب Backend لاحقًا: Provider Name وAPI Key مشفر وModel وحالة الاتصال وتمكين/تعطيل.</p></section>
<section id="sources" class="panel"><div class="section-heading"><h2>مصادر الإشارات</h2><span class="badge neutral">Backend API مطلوب</span></div>${empty('لم يتم إعداد مصدر إشارات')}<p class="subtle">يتطلب Backend لاحقًا إدارة Telegram Bot Token وChannel/Group وحالة الاتصال.</p></section>
<section id="workflow" class="panel"><div class="section-heading"><h2>سير العمل</h2><span class="subtle">لا توجد telemetry API حالياً</span></div><ol class="workflow">${['Market Data','Signal Detection','Alpha Engine','Strategy','Risk Engine','Position Sizing','Order Execution','Position Monitoring','TP / SL Management','Trade Journal / Reports'].map((s,i)=>`<li><b>${i+1}. ${s}</b><span class="badge neutral">غير متاح</span></li>`).join('')}</ol></section>
<section id="backtesting" class="panel"><h2>Backtesting</h2>${empty('لا توجد نتائج Backtesting متاحة حالياً')}</section>
<section id="reports" class="panel"><h2>التقارير</h2>${empty('لا توجد تقارير متاحة حالياً')}</section>
<section id="notifications" class="panel"><h2>التنبيهات وسجل الأحداث</h2><ul id="notifications-list" class="notifications"><li>${empty('لا توجد تنبيهات حالياً')}</li></ul></section>
<section id="settings" class="panel"><div class="section-heading"><h2>الإعدادات</h2><span class="subtle">Configuration Center</span></div><div class="settings-grid">${['حسابات التداول','AI Providers','مصادر الإشارات','الاستراتيجيات','إعدادات المخاطر','التنبيهات','إعدادات المستخدم','الأمان','الأجهزة','Server / VPS','النسخ الاحتياطي','إعدادات النظام'].map(x=>`<a href="#accounts">${x}<small>يفتح عند توفر API مناسب</small></a>`).join('')}</div></section>
</main><nav class="bottom-nav">${[['overview','الرئيسية'],['markets-view','الأسواق'],['positions','المراكز'],['strategies','الاستراتيجيات'],['settings','الإعدادات']].map(([id,label],i)=>`<a class="${i===0?'active':''}" href="#${id}">${label}</a>`).join('')}</nav></div></div>
<dialog id="kill-modal"><h2>تفعيل Kill Switch</h2><p>هل أنت متأكد من تفعيل Kill Switch؟ سيتم منع فتح صفقات جديدة وإيقاف العمليات الآلية. لن يتم إغلاق الصفقات المفتوحة تلقائياً.</p><p class="subtle">لا يوجد Kill Switch API حقيقي في Backend الحالي، ولذلك لا يمكن للواجهة تنفيذ عملية وهمية.</p><form method="dialog"><button value="cancel" class="text-button">إلغاء</button><button value="confirm" class="danger" disabled title="API غير متاح">تأكيد الإيقاف</button></form></dialog>
<dialog id="login-modal"><h2>تسجيل الدخول</h2><p id="login-message" class="subtle">أدخل بيانات حسابك. تحفظ الجلسة في Cookie آمن من Backend.</p><form id="login-form"><label>اسم المستخدم أو البريد<input name="username" autocomplete="username" placeholder="أدخل اسم المستخدم أو البريد" required></label><label>كلمة المرور<input name="password" type="password" autocomplete="current-password" placeholder="أدخل كلمة المرور" required></label><button type="submit">دخول</button><button type="button" class="text-button" id="close-login">إلغاء</button></form></dialog>`;
const escapeHtml=(value:string)=>value.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]??c));
function showLogin(message:string){const modal=document.querySelector<HTMLDialogElement>('#login-modal')!;document.querySelector('#login-message')!.textContent=message;if(!modal.open)modal.showModal()}
async function loadAccounts(){const node=document.querySelector('#accounts-list')!;try{const accounts=await api<ApiAccount[]>('/api-accounts');node.innerHTML=accounts.length?table(['Account','Exchange','Market','Status','IP Security','Permissions','Last Check']):empty('لم يتم ربط أي حساب تداول');if(accounts.length){const row=node.querySelector('tbody tr')!;row.remove();const tbody=node.querySelector('tbody')!;tbody.innerHTML=accounts.map(a=>`<tr><td>${escapeHtml(a.name)}</td><td>Binance</td><td>${escapeHtml(a.market)}</td><td>${a.enabled?'Configured':'Not Connected'}</td><td>غير متاح</td><td>غير متاح</td><td>${a.last_check??'—'}</td></tr>`).join('')}}catch(error){node.innerHTML=empty(error instanceof Error?escapeHtml(error.message):undefined)}}
async function loadStatus(){try{const [health,readiness]=await Promise.all([fetch(`${apiBase}/health`,{credentials:'include'}).then(r=>r.json() as Promise<Health>),api<Readiness>('/live-readiness')]);const system=document.querySelector('#system-status')!;system.textContent=health.status==='ok'?'🟢 ONLINE':'🔴 OFFLINE';system.className=`badge ${health.status==='ok'?'safe':'blocked'}`;const risk=document.querySelector('#risk-status')!;risk.textContent=readiness.allowed?'SAFE':'BLOCKED';risk.className=`badge ${readiness.allowed?'safe':'blocked'}`;document.querySelector('#readiness-reason')!.textContent=readiness.reason}catch{document.querySelector('#system-status')!.textContent='🔴 OFFLINE';document.querySelector('#readiness-reason')!.textContent='تعذر الحصول على قرار المخاطر من الخادم.'}}
(document.querySelector('#account-form') as HTMLFormElement).addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;const submit=document.querySelector<HTMLButtonElement>('#account-submit')!;const status=document.querySelector('#account-status')!;submit.disabled=true;status.textContent='جار الحفظ المشفر…';try{const result=await api<{message:string}>('/api-accounts',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});form.reset();status.textContent=result.message;await loadAccounts()}catch(error){status.textContent=error instanceof Error?error.message:'تعذر حفظ الحساب'}finally{submit.disabled=false}});
(document.querySelector('#strategy-form') as HTMLFormElement).addEventListener('submit',async event=>{event.preventDefault();const file=new FormData(event.currentTarget).get('file');if(!(file instanceof File))return;const body=new FormData();body.append('file',file);const output=document.querySelector('#scan-result')!;const status=document.querySelector('#scan-status')!;const submit=document.querySelector<HTMLButtonElement>('#scan-submit')!;submit.disabled=true;status.textContent='جار الفحص…';try{const result=await api<StrategyScan>('/strategies/scan',{method:'POST',body});status.textContent=`تم استلام نتيجة الفحص: ${result.status}`;output.textContent=JSON.stringify(result,null,2)}catch(error){status.textContent=error instanceof Error?error.message:'تعذر فحص الملف';output.textContent=''}finally{submit.disabled=false}});
document.querySelector('#logout')!.addEventListener('click',async()=>{try{await api('/auth/logout',{method:'POST'});showLogin('تم تسجيل الخروج.')}catch(error){alert(error instanceof Error?error.message:'تعذر تسجيل الخروج')}});document.querySelector('#kill-switch')!.addEventListener('click',()=>document.querySelector<HTMLDialogElement>('#kill-modal')!.showModal());document.querySelector('#user-menu')!.addEventListener('click',()=>showLogin('أدخل بيانات الدخول للمتابعة.'));document.querySelector('#close-login')!.addEventListener('click',()=>document.querySelector<HTMLDialogElement>('#login-modal')!.close());(document.querySelector('#login-form') as HTMLFormElement).addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget;const button=form.querySelector<HTMLButtonElement>('button[type=submit]')!;button.disabled=true;try{await api('/auth/login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});document.querySelector<HTMLDialogElement>('#login-modal')!.close();await loadAccounts();await loadStatus()}catch(error){showLogin(error instanceof Error?error.message:'تعذر تسجيل الدخول')}finally{button.disabled=false}});document.querySelector('#add-account')!.addEventListener('click',()=>document.querySelector<HTMLDetailsElement>('#account-details')!.open=true);
function websocket(){const connection=document.querySelector('#connection')!;connection.textContent='🟡 RECONNECTING';connection.className='badge warning';const protocol=location.protocol==='https:'?'wss':'ws';const wsBase=import.meta.env.VITE_WS_BASE_URL??`${protocol}://${location.host}`;const socket=new WebSocket(`${wsBase}/api/v1/ws/notifications`);socket.onopen=()=>{connection.textContent='🟢 LIVE';connection.className='badge safe'};socket.onmessage=event=>{const data=JSON.parse(event.data) as {message?:string};const item=document.createElement('li');item.textContent=data.message??'تنبيه جديد';document.querySelector('#notifications-list')!.prepend(item)};socket.onclose=()=>setTimeout(websocket,3000);socket.onerror=()=>{connection.textContent='🔴 OFFLINE';connection.className='badge blocked'}}
void loadAccounts();void loadStatus();websocket();
